#!/usr/bin/env node
/**
 * Installs a pre-commit hook that runs lint-staged on THIS theme, in any layout:
 *   - theme IS the git root (standalone theme repo), or
 *   - theme is a SUBDIRECTORY (Pantheon / full-site repo).
 *
 * Auto-runs via the theme's `prepare` script on `npm install`.
 * Safe no-op when there is no git repo or in CI — never fails the install.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, chmodSync } from 'node:fs';
import { join, relative } from 'node:path';

try {
  if (process.env.CI) process.exit(0);

  const gitRoot = execFileSync('git', ['rev-parse', '--show-toplevel'], {
    stdio: ['ignore', 'pipe', 'ignore'],
  })
    .toString()
    .trim();
  if (!gitRoot) process.exit(0);

  // POSIX-relative path from the git root to this theme (for the hook's `cd`).
  const rel = relative(gitRoot, process.cwd()).split(/[\\/]/).join('/');
  const cdTarget = rel === '' ? '.' : rel;

  const hooksDir = join(gitRoot, '.githooks');
  mkdirSync(hooksDir, { recursive: true });

  const hookPath = join(hooksDir, 'pre-commit');
  writeFileSync(
    hookPath,
    `#!/usr/bin/env sh
# Auto-generated by <theme>/scripts/install-git-hooks.mjs — do not edit by hand.
# Format staged theme files (Tailwind class order + Blade) before commit.
# Runs from the theme dir, so lint-staged is scoped to the theme only.
cd "${cdTarget}" && npx lint-staged
`,
  );
  chmodSync(hookPath, 0o755);

  // core.hooksPath is resolved relative to the git root's working tree.
  execFileSync('git', ['-C', gitRoot, 'config', 'core.hooksPath', '.githooks']);

  console.log(`[hooks] pre-commit installed → ${hookPath} (lint-staged in ./${cdTarget})`);
} catch {
  // Never break `npm install` if hooks can't be set up.
  process.exit(0);
}
