<?php

namespace App\Blocks;

class BlockAttributes
{
    private static ?array $grounds = null;

    public static function enum(array $attributes, string $key, array $allowed, string $fallback): string
    {
        $value = $attributes[$key] ?? '';

        return in_array($value, $allowed, true) ? $value : $fallback;
    }

    /**
     * The project's grounds from kit.config.json (`{name, token, light}`),
     * cached for the request. Empty until the design system phase fills them
     * in — every method below degrades to "not a ground" rather than guessing.
     */
    public static function grounds(): array
    {
        if (self::$grounds !== null) {
            return self::$grounds;
        }

        $path = get_template_directory().'/kit.config.json';
        $config = file_exists($path) ? json_decode((string) file_get_contents($path), true) : [];

        return self::$grounds = $config['grounds'] ?? [];
    }

    /** @return string[] */
    public static function groundNames(): array
    {
        return array_column(self::grounds(), 'name');
    }

    /**
     * The class a `.ground-<name>` rule in resources/css/global/grounds.css
     * backs (generated by kit-setup.mjs from the same config), or '' for an
     * unknown ground so a stale saved value never prints a dead class. A dark
     * ground also gets `on-dark`, the hook forms and buttons use to switch to
     * their light-on-dark colors.
     */
    public static function groundClass(string $ground): string
    {
        if (! in_array($ground, self::groundNames(), true)) {
            return '';
        }

        return self::isLightGround($ground) ? "ground-{$ground}" : "ground-{$ground} on-dark";
    }

    /**
     * '' (no ground chosen) and an unknown/stale ground both mean "the
     * normal page," which is light — not dark. Only a ground actually
     * configured with light: false counts as dark.
     */
    public static function isLightGround(string $ground): bool
    {
        foreach (self::grounds() as $entry) {
            if (($entry['name'] ?? null) === $ground) {
                return (bool) ($entry['light'] ?? false);
            }
        }

        return true;
    }

    /**
     * The btn family a CTA reads on a given ground: 'btn-primary' on a light
     * backdrop, 'btn-on-dark' on a dark one. $tone overrides the ground check
     * for a block like cta-banner, whose backdrop (a photo, or a flat
     * fallback) isn't a configured ground — it names its own text tone
     * ('light' text implies a dark backdrop) instead.
     */
    public static function ctaButtonClass(string $ground, ?string $tone = null): string
    {
        $isLight = $tone !== null ? $tone !== 'light' : self::isLightGround($ground);

        return $isLight ? 'btn-primary' : 'btn-on-dark';
    }

    /**
     * The call-to-action keys every block that has one reads from Blade,
     * lifted out of the block.php copies that each built this by hand.
     */
    public static function cta(array $attributes): array
    {
        return [
            'ctaText' => sanitize_text_field($attributes['ctaText'] ?? ''),
            'ctaUrl' => esc_url_raw($attributes['ctaLink']['url'] ?? ''),
            'ctaNew' => (bool) ($attributes['ctaLink']['opensInNewTab'] ?? false),
            'ctaIconClass' => self::ctaIconClass(
                (string) ($attributes['ctaIcon'] ?? ''),
                (string) ($attributes['ctaIconPosition'] ?? ''),
            ),
        ];
    }

    /**
     * Twin of ctaIconClass() in components/backend/ActionEditor.jsx, so the
     * editor preview and the front end agree on the class an icon choice
     * prints.
     */
    public static function ctaIconClass(string $icon, string $position): string
    {
        if (! in_array($icon, ['arrow', 'external', 'download'], true)) {
            return '';
        }

        return 'btn-icon-'.$icon.($position === 'before' ? ' btn-icon-before' : '');
    }

    /**
     * Rich copy an editor wrote, already filtered, with the hidden new-tab
     * text after the label of every `<a target="_blank">`. Twin of
     * resources/views/partials/new-tab-hint.blade.php, which does the same for
     * a link a block prints itself. Every block that prints rich copy passes it
     * through here, and conformance renders a new-tab link in it to check.
     */
    public static function newTabHints(string $html): string
    {
        if (stripos($html, '_blank') === false) {
            return $html;
        }

        $hint = '<span class="sr-only"> '.esc_html(__('(opens in a new tab)', '__TEXT_DOMAIN__')).'</span>';

        // A `>` inside a quoted attribute doesn't end the tag.
        return preg_replace_callback(
            '#(<a\b(?:[^>"\']|"[^"]*"|\'[^\']*\')*>)(.*?)(</a>)#is',
            fn (array $link) => preg_match('#\starget\s*=\s*(["\']?)_blank\1(?=[\s/>])#i', $link[1]) && ! str_ends_with($link[2], $hint)
                ? $link[1].$link[2].$hint.$link[3]
                : $link[0],
            $html,
        );
    }

    public static function divider(array $attributes): string
    {
        return self::enum($attributes, 'sectionDivider', ['none', 'above', 'below'], 'none');
    }

    /**
     * The rule a resolved divider prints on the section root. Twin of
     * dividerClass() in components/backend/DividerControl.jsx.
     */
    public static function dividerClass(string $divider): string
    {
        return match ($divider) {
            'above' => 'border-t-2 border-[color:var(--color-primary)]',
            'below' => 'border-b-2 border-[color:var(--color-primary)]',
            default => '',
        };
    }
}
